url: https://mickeybeurskens.nl
baseurl:

# Site settings
title: Mickey Beurskens
email: info@mickeybeurskens.nl
description: "I am a programmer and robotics engineer interested in automation. I like to work on CI/CD systems and automating the boring stuff. Next to that I work on robotic systems to supercharge productivity."


# Team names, titles and social links
people:
- name: Mickey Beurskens
  pic: 1
  position: Programmer - Robotics Engineer - AI Enthousiast
  social:
    - title: github
      url: https://github.com/GnomeBlue
    - title: linkedin
      url: https://www.linkedin.com/in/mickey-beurskens/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: github
      url: https://github.com/GnomeBlue
    - title: linkedin
      url: https://www.linkedin.com/in/mickey-beurskens/

# Postal address (add as many lines as necessary)
address:
  - line: Eindhoven
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
